name: Scheduled Crowdin Sync

on:
    schedule:
        - cron: '0 */12 * * *' # Sync every 12 hours - https://crontab.guru/#0_*/12_*_*_*
    workflow_dispatch: # For manually running the action

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    permissions:
        contents: write

    steps:
          - name: Checkout 
            uses: actions/checkout@v3

          - name: Crowdin Action
            uses: crowdin/github-action@1.4.7
            with:
                upload_sources: false
                upload_translations: false
                download_translations: true
                skip_untranslated_strings: true
                create_pull_request: false
                source: locale/en.json
                translation: locale/%two_letters_code%.json
                project_id: ${{ secrets.CROWDIN_PROJECT_ID }}
                token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
          - name: Commit Translation Updates
            uses: stefanzweifel/git-auto-commit-action@v4
            with:
                commit_message: i18n Updates
                commit_user_name: i18n Bot
                commit_user_email: stardustclarity@gmail.com
                commit_author: i18n Bot <stardustclarity@gmail.com>